### ISSUE TITLE
Missing some French Gherkin keywords

### ISSUE THREAD

**Issue by DavidBeaumier** [euclidity/vscode-cucumber#12]
I was really happy to find an extension that supports Gherkin keywords for many languages. However, there's a little problem with some of the French keywords.

If I start a scenario with the keywords "Étant donné" (given) these keywords are not recognized even if I they are defined in the feature.tmLanguage file. 

Strangely, when using the "Etant donné" keywords I get colorized syntax. Thus, it doesn't seem to be an accent problem (or maybe it's an uppercase + accent issue ?) 

![image](https://cloud.githubusercontent.com/assets/3083902/20779775/b0866d86-b744-11e6-8f24-38db25c4ee7d.png)

**Comment by dialex** [comment]
This is related with #14. Let's use that issue to track our multi-language support efforts.

It would be great if the community helped us with pull requests for each language. We will be more than happy to review them.
