### ISSUE TITLE
Feature: Snippets for commonly used actions of given/when/then

### ISSUE THREAD

**Issue by cchitsiang** [euclidity/vscode-cucumber#13]
Not sure if anyone interested on this. 

Inspiration from this article http://shashikantjagtap.net/speed-up-your-bdd-with-sublime-text-2/
![image](https://cloud.githubusercontent.com/assets/343107/21538520/dc9f36f0-cdd8-11e6-9590-6209e99ae96c.png)

**Comment by dialex** [comment]
That's an interesting idea, definitely more useful than a snippet that just autocompletes the word "Given" or "When". Thanks for suggesting it.

More than a year passed and no one upvoted your feature request, so I'll assume that's something that community does not consider critical. Therefore we won't code that feature.

If anyone wants to do a pull request with that, we'll be more than happy to review it.
