### ISSUE TITLE
multiple cursors created in final scenario placeholder.

### ISSUE THREAD

**Issue by jamesharris-garmin** [euclidity/vscode-cucumber#23]
https://github.com/euclidity/vscode-cucumber/blob/0910b662514601188beb2f158f143545d4ff3464/snippets/snippets.json#L40

It looks like the scenarios snippet uses $0 twice at the end. This results in creating multiple cursors for the final snippet location at exit.   Was this intended? maybe you wanted `\r\n\r\n$0`  instead of `\r\n$0\r\n$0`.

I can probably post a fix for this if you would like.

**Comment by dialex** [comment]
Looks like a typo indeed.
Yes please, if you can create a Pull Request, it's a lot faster on our side ;)

**Comment by jamesharris-garmin** [comment]
Alright. I updated the pull request.
