### ISSUE TITLE
Does not install from vscode extension menu

### ISSUE THREAD

**Issue by tdbenson** [euclidity/vscode-cucumber#25]
When I click install I get this error:
![image](https://user-images.githubusercontent.com/17076076/67782084-b7330000-fa3e-11e9-8f44-f1cce13eb32e.png)

It looks like the install button points to stevejpurves.cucumber and not euclidity.vscode-cucumber?

**Comment by dialex** [comment]
Cannot reproduce. I was able to install through VS Code and the [website](https://marketplace.visualstudio.com/items?itemName=stevejpurves.cucumber) as well:

![demo](https://user-images.githubusercontent.com/2140450/68025455-aa174a80-fca4-11e9-8e68-c52c499c171b.gif)

Try installing again. Or updating VS Code first. Or restarting your machine. 🤷‍♂
