### ISSUE TITLE
Apostrophe breaks syntax highlighting

### ISSUE THREAD

**Issue by jreadytalk** [euclidity/vscode-cucumber#3]
Syntax highlighting breaks when a step contains an individual apostrophe (single-quote) or an individual double quote. For example, the apostrophe on "1's" causes the remainder of the file to be peach colored:

![screen shot 2016-03-08 at 2 55 14 pm](https://cloud.githubusercontent.com/assets/8117740/13620512/a1ce8996-e54d-11e5-9181-df057573be33.png)

The same happens with purposefully-individual double quotes.

**Comment by deinman** [comment]
Looks like this only happens when the apostraphe follows an integer.

**Comment by stevejpurves** [comment]
fix available in 0.9.5 thanks to @JVimes
