### ISSUE TITLE
Support for Comments

### ISSUE THREAD

**Issue by seantdg** [euclidity/vscode-cucumber#4]
Given I am a Cucumber developer
And I use Windows
And I select a line
When I press Ctrl + /
Then the selected lines should be commented

Given I am a Cucumber developer
And I use Mac
And I select a line
When I press Cmd + /
Then the selected lines should be commented

:)

**Comment by seantdg** [comment]
I see this is listed under Known Issues - thanks

**Comment by gferreri** [comment]
Hi guys -- I created a PR that adds this ability. Cheers.

**Comment by stevejpurves** [comment]
thanks @gferreri i'll be able to get it merged and an updaed release out soon!
